name: ContinuousIntegrationOtherBranches

on: 
  push:
    branches-ignore: [master]

jobs: 
  ContinuousIntegrationOtherBranches: 
    runs-on: [ubuntu-latest]
    steps: 
      - run: echo Runing test
      - run: echo npm install
      - run: echo npm start
      - run: echo npm test